'use strict';

export const GET_FLIGHTS_REQUEST = 'GET_FLIGHTS_REQUEST';
export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS';

export const GET_DEPARTURE_FLIGHTS = 'GET_DEPARTURE_FLIGHTS';
export const GET_ARRIVAL_FLIGHTS = 'GET_ARRIVAL_FLIGHTS';

export const EDIT_FLIGHT = 'EDIT_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
